python ../codes/train.py --data_dir ../dataset/docred/ \
                --transformer_type roberta  \
                --model_name_or_path microsoft/deberta-v2-xlarge \
                --train_file train_annotated.json  \
                --dev_file dev.json \
                --test_file test.json \
                --train_batch_size 4 \
                --test_batch_size 4 \
                --gradient_accumulation_steps 1 \
                --num_labels 4 \
                --learning_rate 2e-5 \
                --max_grad_norm 1.0 \
                --warmup_ratio 0.1 \
                --num_train_epochs 5.0 \
                --seed 66 \
                --num_class 97 \
                --gpu 1 \
                --tau 2.0 \
                --tau_base 1.0 \
                --save_path ../checkpoints/docred.pt